#!/bin/bash

LOG_FILE="/var/log/nginx/access.log"

awk '
BEGIN {
    FS="[& ]";
    OFS="\t";
}
/location=/ {
    location[$2]++;
    date[$6]++;
}
END {
    print "Location\t" "Date\t" "Hits";
    for (loc in location) {
        for (d in date) {
            print loc, d, location[loc" date="d];
        }
    }
}
' $LOG_FILE | sort -k1,2
